env:
  browser: true
  commonjs: true
  es2021: true
extends:
  - google
  - prettier
parser: "@typescript-eslint/parser"
parserOptions:
  ecmaVersion: 12
plugins:
  - "@typescript-eslint"
rules: {
  "complexity": ["error", 20],
  "require-jsdoc": ["off"]
}
